development:
  access_key_id: <%= ENV["RIB_S3_KEY"] %> 
  secret_access_key: <%= ENV["RIB_S3_SECRET"] %>
  bucket: ribbon-files

production:
  access_key_id: <%= ENV["RIB_S3_KEY"] %> 
  secret_access_key: <%= ENV["RIB_S3_SECRET"] %>
  bucket: ribbon-files