# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8a7d3320f72a03b19c1fe2d2a0d7535a672d06738a23c86bac68e07c75a136ab49d3300a55a7805bfad52fc7ecd7dee228fe20a05b380a5f84017af595fd9d5

test:
  secret_key_base: f57f92e5dc27ca2f3c4f8a5673917999fcfb6515f58a40fab198a3374f377e265f0c6356efc1a2fee8c2b485d42bab8bc29bc6fd5a9ae824e8180414edb8651d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
